M48
; DRILL file {KiCad (6.0.7)} date Fri Sep 30 22:22:35 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-30T22:22:35-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.000
%
G90
G05
T1
X83.82Y-84.795
X104.14Y-84.795
X124.46Y-84.795
X144.78Y-84.795
T0
M30
